#!/usr/bin/env ruby

require 'fileutils'

WHITELIST = '/etc/ban_hammer/whitelist'.freeze
BLACKLIST = '/etc/ban_hammer/blacklist'.freeze

def readlist(filename)
  path = File.dirname(filename)

  FileUtils.mkdir_p(path) unless File.directory?(path)

  l = []

  if File.exist?(filename)
    File.open(filename, 'r').each do |line|
      l << line.chomp
    end
  else
    FileUtils.touch(filename)
  end

  l
end

def readhash(filename)
  x = readlist(filename)

  h = {}
  x.each do |line|
    y = line.split(/\s+/)
    h[y.first] = y.last
  end

  h
end

def save_blacklist(b, ip_address = nil)
  unless ip_address.nil?
    b[ip_address] = Time.now.to_i

    `ufw insert 1 deny from #{ip_address}` unless b.key?(ip_address)
  end

  f = File.open(BLACKLIST, 'w')
  b.each do |ip_address, ts|
    f.puts "#{ip_address} #{ts}"
  end
  f.close
end

def existing
  x = `ufw status numbered`
  h = {}
  x.split("\n").each do |line|
    next unless line.include?('DENY IN')

    line = line.delete('[').delete(']').strip
    y = line.split(/\s+/)
    h[y.last] = y.first
  end
  h
end

w = readlist(WHITELIST)
b = readhash(BLACKLIST)
e = existing

unless ARGV[0]
  puts 'No command given'
  exit(1)
end

cmd = ARGV.shift.downcase

case cmd
when 'update'
  missing = 0

  puts 'Checking that ufw is up to date'
  b.each do |ip_address, _|
    next if e.key?(ip_address)

    puts "-- #{ip_address} was missing"
    missing += 1
    `ufw insert 1 deny from #{ip_address}`
  end
  puts "There are #{b.size} banned addresses, #{missing} were missing"
when 'show'
  puts "Whitelist (#{WHITELIST})"
  w.each do |ip_address|
    puts "- #{ip_address}"
  end
  puts
  puts "Blacklist (#{BLACKLIST})"
  b.each do |ip_address, _|
    puts "- #{ip_address}"
  end
  puts
when 'add'
  # It's an address to ban

  if ARGV[0].nil?
    puts 'No address given to ban'
    exit(1)
  end

  ip_address = ARGV.shift

  if w.include?(ip_address)
    puts "#{ip_address} is in the whitelist"
  elsif b.key?(ip_address)
    puts "#{ip_address} is already blacklisted. Bumping timestamp"
    save_blacklist(b, ip_address)
  else
    puts "#{ip_address} added to blacklist"
    save_blacklist(b, ip_address)
  end
when 'remove'
  # It's an address to unban

  if ARGV[0].nil?
    puts 'No address given to ban'
    exit(1)
  end

  ip_address = ARGV.shift
  found = false

  if b.key?(ip_address)
    b.delete(ip_address)
    save_blacklist(b)
    found = true
  end

  if e.key?(ip_address)
    number = e[ip_address]
    `echo y | ufw delete #{number}`
    found = true
  end

  if found
    puts "#{ip_address} removed from blacklist"
  else
    puts "#{ip_address} is not in the blacklist"
  end
else
  puts "Unknown command [#{cmd}]"
end
